import { type User, type InsertUser, type Property, type ContactForm, type BookingRequest } from "@shared/schema";
import { randomUUID } from "crypto";

export interface IStorage {
  getUser(id: string): Promise<User | undefined>;
  getUserByUsername(username: string): Promise<User | undefined>;
  createUser(user: InsertUser): Promise<User>;
  getProperties(): Promise<Property[]>;
  getProperty(id: string): Promise<Property | undefined>;
  setProperties(properties: Property[]): Promise<void>;
  saveContactForm(form: ContactForm): Promise<void>;
  saveBookingRequest(booking: BookingRequest): Promise<void>;
}

// Properties from Smart Hjem AS portfolio - combined from Booking.com and norges-ferie.no
const realProperties: Property[] = [
  // === EXISTING BEDS24/BOOKING.COM PROPERTIES ===
  {
    id: "smolasen-tjorhom",
    name: "Flott hytte på Smølåsen Tjørhom",
    description: "Flott hytte på Smølåsen Tjørhom i Fidjeland med tre soverom og ett bad. Eiendommen inkluderer et fullt utstyrt kjøkken med kjøleskap, ovn, komfyr, kaffetrakter og vaskemaskin. Gjester kan nyte hage og terrasse med hageutsikt. Hytta har gratis WiFi, balkong og gratis privat parkering. Perfekt for vintersport og naturopplevelser.",
    location: "Fidjeland, Sirdal",
    beds: 4,
    bathrooms: 1,
    maxGuests: 6,
    pricePerNight: 0,
    images: [
      "https://cf.bstatic.com/xdata/images/hotel/max1024x768/613901486.jpg?k=2328dadd869a32aa286eb06af0fb982a8566c5d237111932ac12ed014ef91365&o=",
      "https://cf.bstatic.com/xdata/images/hotel/max500/613901527.jpg?k=5f1b5279508bffb8776050991e836d1f6be8bb3255019a9d0d4c5de0cd6bc769&o=",
      "https://cf.bstatic.com/xdata/images/hotel/max500/613901506.jpg?k=1113d67643b5fc7377636c4d6cb35fd22c7e1f83bc15c4c97aab757b19f6f16b&o=",
    ],
    amenities: ["WiFi", "Gratis Parkering", "Balkong", "Terrasse", "Hage", "Kjøkken", "TV", "Grill", "Vaskemaskin"],
    available: true,
  },
  {
    id: "great-white-bygland",
    name: "Great white cottage in Bygland",
    description: "Koselig feriebolig i Bygland med ett soverom og ett bad. Gjester kan slappe av på terrassen og nyte hageutsikt. Eiendommen har fullt utstyrt kjøkken, TV og gratis WiFi. Gratis privat parkering tilgjengelig. Kjæledyr er velkomne uten ekstra kostnader.",
    location: "Bygland",
    beds: 1,
    bathrooms: 1,
    maxGuests: 5,
    pricePerNight: 0,
    images: [
      "https://cf.bstatic.com/xdata/images/hotel/max1024x768/719171922.jpg?k=f9f20d7e2ab786538397400f8eb5c826f1ef8dda406705e32fa22c3326991d35&o=",
      "https://cf.bstatic.com/xdata/images/hotel/max500/719172389.jpg?k=968cf2cbe50a18ceb283bd1399f2bbf5160abfeffb78bad69f7a12481afd2323&o=",
      "https://cf.bstatic.com/xdata/images/hotel/max500/719172254.jpg?k=64d16210df6cb5e4254027a6dc35f053148b5a64fbb84f648474e925d4b41d10&o=",
    ],
    amenities: ["WiFi", "Gratis Parkering", "Terrasse", "Kjøkken", "TV", "Kjæledyr Tillatt"],
    available: true,
  },
  {
    id: "lind-046-lindesnes",
    name: "Lind 046 - 6 voksne 2 barn",
    description: "Feriebolig i Lindesnes med ett soverom og ett bad. Gjester nyter gratis privat parkering, fullt utstyrt kjøkken, vaskemaskin og TV. Eiendommen har hage med vakker utsikt. Sandvikstranna strand er 17 minutters gange unna, mens Lindesnes fyr ligger 12 km fra ferieboligen.",
    location: "Spangereid, Lindesnes",
    beds: 3,
    bathrooms: 1,
    maxGuests: 6,
    pricePerNight: 0,
    images: [
      "https://cf.bstatic.com/xdata/images/hotel/max1024x768/697230514.jpg?k=80b90bb78f00b6723657113f98a00a4fbee50615219a21297556870c70d4b362&o=",
      "https://cf.bstatic.com/xdata/images/hotel/max500/697230541.jpg?k=d55d100a6de5f33e9efc506db466a657314d6d58c89621bd472e955deef67d6d&o=",
      "https://cf.bstatic.com/xdata/images/hotel/max500/697230677.jpg?k=d4de73f3f45d047ad59e8a925d56a4d992f396d4c77779bafeade06b7631b6bc&o=",
    ],
    amenities: ["Gratis Parkering", "Hage", "Kjøkken", "TV", "Vaskemaskin", "Grill", "Utsikt", "Kjæledyr Tillatt"],
    available: true,
  },
  {
    id: "flott-hytte-bygland",
    name: "Flott hytte på Bygland",
    description: "Koselig feriebolig i Bygland med to soverom og ett bad. Gjester nyter gratis WiFi og fullt utstyrt kjøkken. Eiendommen har balkong med hageutsikt. Gratis privat parkering tilgjengelig.",
    location: "Bygland",
    beds: 6,
    bathrooms: 1,
    maxGuests: 6,
    pricePerNight: 0,
    images: [
      "https://cf.bstatic.com/xdata/images/hotel/max1024x768/679348174.jpg?k=566b7a8b5d5a96fee0c1262be31b927fa66c56d2e666668fc0b8c94d0e3e35f5&o=",
      "https://cf.bstatic.com/xdata/images/hotel/max500/679347957.jpg?k=7757344247a797e802fe20124f95b92e74b3ba81e4bf92d5b58afcf8c2f0472a&o=",
      "https://cf.bstatic.com/xdata/images/hotel/max500/679347986.jpg?k=e250fcf14be672c87a6717fe5feced966240f3755f992883449f0d4869d3f92c&o=",
    ],
    amenities: ["WiFi", "Gratis Parkering", "Balkong", "Kjøkken", "TV", "Utsikt", "Kjæledyr Tillatt"],
    available: true,
  },
  {
    id: "feriehus-sogne",
    name: "Flott feriehus Søgne",
    description: "Feriebolig i Kristiansand med tre soverom og ett bad. Gjester kan nyte hage og terrasse med sjøutsikt. Boligen har fullt utstyrt kjøkken med kjøleskap, mikrobølgeovn, ovn, komfyr og vannkoker.",
    location: "Søgne, Kristiansand",
    beds: 5,
    bathrooms: 1,
    maxGuests: 6,
    pricePerNight: 0,
    images: [
      "https://cf.bstatic.com/xdata/images/hotel/max1024x768/585588418.jpg?k=bdf64ea1f37a428d701092d99a2c982ce79525fec0fac235cc43becb528f4e11&o=",
      "https://cf.bstatic.com/xdata/images/hotel/max500/585588707.jpg?k=a64e1c86435285bea3ea5b9f0544e7bd182ff6a47f5ed2fd941a8dec87b9de49&o=",
      "https://cf.bstatic.com/xdata/images/hotel/max500/585588459.jpg?k=3ec2e200aba6d048f464408a08f94b77a41aa69a155df98787c0f9847fea430a&o=",
    ],
    amenities: ["WiFi", "Sjøutsikt", "Terrasse", "Hage", "Kjøkken", "TV", "Familievennlig", "Kjæledyr Tillatt"],
    available: true,
  },
  {
    id: "koselig-oggevatn",
    name: "Koselig feriehus Oggevatn",
    description: "Romslig feriebolig i Birkenes med fire soverom og stue. Eiendommen inkluderer fullt utstyrt kjøkken, vaskemaskin og koselig peis. Gjester kan nyte vakker hage og utendørs sitteområde.",
    location: "Birkenes",
    beds: 4,
    bathrooms: 1,
    maxGuests: 8,
    pricePerNight: 0,
    images: [
      "https://cf.bstatic.com/xdata/images/hotel/max1024x768/572699655.jpg?k=c6f1a74d06b4b806a0dae8ebf213f7b7f587d19b6228519768a7cddf2e42ce54&o=",
      "https://cf.bstatic.com/xdata/images/hotel/max500/576208876.jpg?k=21c2387a3f9559ab85cee0b4623a2fbd6eaafd350036cf7833398f6d8c11825b&o=",
      "https://cf.bstatic.com/xdata/images/hotel/max500/576208855.jpg?k=21bd0c824b792a6c350a79a63a5359b916dacdac80b91937afc4438e3be5c290&o=",
    ],
    amenities: ["WiFi", "Gratis Parkering", "Flyplasstransport", "Hage", "Kjøkken", "TV", "Peis", "Vaskemaskin", "Familievennlig", "Grill"],
    available: true,
  },
  
  // === BEDS24 / BOOKING.COM PROPERTIES ===
  {
    id: "feriehus-oksnevik",
    name: "Feriehus - Øksnevik Lindesnes",
    description: "Feriebolig i Grønsfjord/Øksnevik, Lindesnes med 3 soverom og panoramautsikt over Grønsfjorden. Fullt utstyrt kjøkken, balkong og terrasse med sjøutsikt. Tilgang til båtplass, fileteringsanlegg og badestrand. Volleyball og lekeplass i området.",
    location: "Grønsfjord, Lindesnes",
    beds: 4,
    bathrooms: 2,
    maxGuests: 8,
    pricePerNight: 0,
    images: [
      "https://image.novasol.com/pic/600/n36/n36331_main_01.jpg",
      "https://image.novasol.com/pic/600/n36/n36331_view_01.jpg",
      "https://image.novasol.com/pic/600/n36/n36331_kitchen_01.jpg",
      "https://image.novasol.com/pic/600/n36/n36331_main_02.jpg",
      "https://image.novasol.com/pic/600/n36/n36331_outdoor_01.jpg",
    ],
    amenities: ["WiFi", "Gratis Parkering", "Terrasse", "Balkong", "Panoramautsikt", "Sjøutsikt", "Kjøkken", "TV", "Båtplass", "Lekeplass", "Oppvaskmaskin"],
    available: true,
    bookingUrl: "https://www.booking.com/hotel/no/feriehus-oksnevik-lindesnes.html",
  },
  {
    id: "feriehus-arendal",
    name: "Feriehus - Arendal ved sjøen",
    description: "Feriebolig ved sjøen i Arendal med 2 soverom og 2 bad. Romslig leilighet med innsjø- og hageutsikt. Gratis WiFi, hage og strandnært beliggenhet. Perfekt for en avslappende ferie på Sørlandet.",
    location: "Arendal",
    beds: 2,
    bathrooms: 2,
    maxGuests: 5,
    pricePerNight: 0,
    images: [
      "https://cf.bstatic.com/xdata/images/hotel/max1024x768/572699655.jpg?k=c6f1a74d06b4b806a0dae8ebf213f7b7f587d19b6228519768a7cddf2e42ce54&o=",
      "https://cf.bstatic.com/xdata/images/hotel/max500/576208876.jpg?k=21c2387a3f9559ab85cee0b4623a2fbd6eaafd350036cf7833398f6d8c11825b&o=",
      "https://cf.bstatic.com/xdata/images/hotel/max500/576208855.jpg?k=21bd0c824b792a6c350a79a63a5359b916dacdac80b91937afc4438e3be5c290&o=",
    ],
    amenities: ["WiFi", "Gratis Parkering", "Sjøutsikt", "Hage", "Kjøkken", "TV", "Strandnært"],
    available: true,
    bookingUrl: "https://www.booking.com/hotel/no/feriehus-arendal-ved-sjoen.html",
  },
  {
    id: "vakker-spindfjorden",
    name: "Vakker ferie ved Spindfjorden",
    description: "Vakker feriebolig ved Spindfjorden i Farsund med 3 soverom og 1 bad. 90 m² med balkong/terrasse og hageutsikt. Gratis WiFi, grillfasiliteter og gratis parkering. Perfekt for en rolig ferie ved fjorden.",
    location: "Spindfjorden, Farsund",
    beds: 3,
    bathrooms: 1,
    maxGuests: 6,
    pricePerNight: 0,
    images: [
      "https://q-xx.bstatic.com/xdata/images/hotel/max1024x768/560011810.jpg?k=57c8b25adf5c49c2474cabe50619c8436aa93ba561716152cad9511a233b737e&o=",
      "https://q-xx.bstatic.com/xdata/images/hotel/max1024x768/560012063.jpg?k=78f1019e0051c75f27d89bece8ddf43c11db31d594d9ae1fbb2c8a15953ae8c7&o=",
      "https://q-xx.bstatic.com/xdata/images/hotel/max1024x768/560011916.jpg?k=9ec5a252d74f3dc2028babe7d2fe50e16fe8c5169aa3e57021081a859b0f6441&o=",
      "https://q-xx.bstatic.com/xdata/images/hotel/max1024x768/560012027.jpg?k=ab5f51e8e46ee7ad2423f1b012c41408c24702c30bca207793e9a70af0099df9&o=",
    ],
    amenities: ["WiFi", "Gratis Parkering", "Balkong", "Terrasse", "Grill", "Kjøkken", "Hageutsikt"],
    available: true,
    bookingUrl: "https://www.booking.com/hotel/no/vakker-ferie-ved-spindfjorden.html",
  },
  {
    id: "lind-004",
    name: "Lind 004 - 6 pers",
    description: "Flott leilighet i Åvik, Lindesnes kommune, helt ytterst ved havet i naturskjønne omgivelser. Koselig innredet og meget godt utstyrt med 3 soverom. Utsikt mot havet fra stuevinduet. Solrikt med flott turterreng. Båtplass på Åvik Brygge.",
    location: "Åvik, Lindesnes",
    beds: 3,
    bathrooms: 2,
    maxGuests: 6,
    pricePerNight: 0,
    images: [
      "https://www.norges-ferie.no/upload/images/lind_004_ny/lind%20004%201.jpeg",
      "https://www.norges-ferie.no/upload/images/lind_004_ny/Lind%20004%202.jpeg",
      "https://www.norges-ferie.no/upload/images/lind_004_ny/Lind%20004%203.jpeg",
      "https://www.norges-ferie.no/upload/images/lind_004_ny/Lind%20004%20Terrasse.jpg",
      "https://www.norges-ferie.no/upload/images/lind_004_ny/Lind%20004%20Utsikt.jpeg",
    ],
    amenities: ["Sjøutsikt", "Terrasse", "Båtplass", "Gratis Parkering", "Kjøkken", "TV", "WiFi", "Oppvaskmaskin", "Vaskemaskin", "Lekeplass"],
    available: true,
    externalUrl: "https://www.norges-ferie.no/lind-004-6-pers",
  },
  {
    id: "lind-006",
    name: "Lind 006 - 10 pers",
    description: "Fantastisk hytte på Urvikodden i Lindesnes, helt ytterst i havgapet med nydelig utsikt mot sjøen. 4 soverom og 2 terrasser. Peis, parabol og moderne fasiliteter. Båtplass 50 meter fra hytta. Perfekt for familier og sportsfiskere.",
    location: "Urvikodden, Lindesnes",
    beds: 5,
    bathrooms: 1,
    maxGuests: 10,
    pricePerNight: 0,
    images: [
      "https://www.norges-ferie.no/upload/images/lind_006_new/lind_006a.jpg",
      "https://www.norges-ferie.no/upload/images/lind_006_new/Lind%20006%20Hoved_Easy-Resize.com.jpg",
      "https://www.norges-ferie.no/upload/images/lind_006_new/Lind%20006%20Terrasse_Easy-Resize.com.jpg",
      "https://www.norges-ferie.no/upload/images/lind_006_new/Lind%20006%20Solnedgang_Easy-Resize.com.jpg",
      "https://www.norges-ferie.no/upload/images/lind_006_new/Lind%20006%20Utsikt%20fra%20Terrasse_Easy-Resize.com.jpg",
    ],
    amenities: ["Sjøutsikt", "Terrasse", "Båtplass", "Peis", "Gratis Parkering", "Kjøkken", "TV", "WiFi", "Oppvaskmaskin", "Vaskemaskin"],
    available: true,
    externalUrl: "https://www.norges-ferie.no/lind-006-8-pers",
  },
  {
    id: "lind-009",
    name: "Lind 009 - 4 pers",
    description: "Sjarmerende lite hus i Åvik, Lindesnes, helt ytterst i havgapet. 2 soverom, koselig innredet og godt utstyrt. Utsikt til Øvrestranda i Åvik. Perfekt for uberørt skjærgårdsidyll med holmer og solslitte svaberg. Båtleie tilgjengelig på Åvik Brygge.",
    location: "Åvik, Lindesnes",
    beds: 2,
    bathrooms: 1,
    maxGuests: 4,
    pricePerNight: 0,
    images: [
      "https://www.norges-ferie.no/upload/images/lind_009_new/img_4705.jpg",
      "https://www.norges-ferie.no/upload/images/lind_009_new/IMG_4673.jpg",
      "https://www.norges-ferie.no/upload/images/lind_009_new/IMG_4674.jpg",
      "https://www.norges-ferie.no/upload/images/lind_009_new/IMG_4678.jpg",
      "https://www.norges-ferie.no/upload/images/lind_009_new/IMG_4681.jpg",
    ],
    amenities: ["Sjøutsikt", "Båtplass", "Peis", "Gratis Parkering", "Kjøkken", "TV", "WiFi", "Oppvaskmaskin", "Vaskemaskin", "Lekeplass"],
    available: true,
    externalUrl: "https://www.norges-ferie.no/lind-009-6-pers",
  },
  {
    id: "feriehus-lauvbakken-moi",
    name: "Feriehus Lauvbakken Moi",
    description: "Feriebolig på Lauvbakken i Lund med strandfront og to soverom. Gjester nyter gratis WiFi, balkong med innsjøutsikt og fullt utstyrt kjøkken. Eiendommen har peis og hage.",
    location: "Tjellesvik, Lund",
    beds: 2,
    bathrooms: 1,
    maxGuests: 4,
    pricePerNight: 0,
    images: [
      "https://cf.bstatic.com/xdata/images/hotel/max1024x768/559999485.jpg?k=0670a72c7f748b075cf565fef68381c19243a2fd1bb633392f353340a9f950aa&o=",
      "https://cf.bstatic.com/xdata/images/hotel/max500/697566697.jpg?k=43df7fe7be4069b2d7304c10a35ae3680f7ae30bb5e0d25b16d9126d661ae18b&o=",
      "https://cf.bstatic.com/xdata/images/hotel/max500/559999550.jpg?k=e5e0f32e698585e6a88fa51083a005c343c709d3768f033995982e708291981f&o=",
    ],
    amenities: ["WiFi", "Strandfront", "Balkong", "Hage", "Kjøkken", "TV", "Peis", "Kjæledyr Tillatt", "Utsikt"],
    available: true,
  },
  {
    id: "dobbel-feriehus-bortelid",
    name: "Dobbel Feriehus - Bortelid/Åseral",
    description: "Romslig feriehus på Bortelid i Åseral med fire soverom og to bad. Eiendommen inkluderer boblebad og spa. Gjester nyter gratis WiFi, solterrasse og hage.",
    location: "Tjaldal, Åseral",
    beds: 5,
    bathrooms: 2,
    maxGuests: 8,
    pricePerNight: 0,
    images: [
      "https://cf.bstatic.com/xdata/images/hotel/max1024x768/550165626.jpg?k=a8b32c3dbfac1aa615f1f9e3f3682691f6cff35d1ef0dba26d5abaebf0fd6b90&o=",
      "https://cf.bstatic.com/xdata/images/hotel/max500/571448223.jpg?k=ca6e46617c04e5280beea503918ea1af779a74dee297add4a2d6d041523058b1&o=",
      "https://cf.bstatic.com/xdata/images/hotel/max500/571447485.jpg?k=7bf5dffbc040596beb8fd43955a99a078cafd8cf021a3331fb0a3fadf0d48742&o=",
    ],
    amenities: ["WiFi", "Gratis Parkering", "Boblebad", "Spa", "Solterrasse", "Hage", "Kjøkken", "TV", "Vaskemaskin", "Familievennlig"],
    available: true,
  },
  {
    id: "flott-feriehus-tjorhom",
    name: "Flott Feriehus - Tjørhom",
    description: "Romslig feriehus i Tjørhom, Sirdal med fire soverom og to bad. Eiendommen har stue med sofaer og familievennlige rom. Gjester nyter gratis WiFi, hage og terrasse med fjell- og hageutsikt.",
    location: "Sinnes, Sirdal",
    beds: 7,
    bathrooms: 2,
    maxGuests: 9,
    pricePerNight: 0,
    images: [
      "https://cf.bstatic.com/xdata/images/hotel/max1024x768/526487530.jpg?k=21581f8f8572e3d9941d774eef182b141430d12ddd707ccfad48a0351138c606&o=",
      "https://cf.bstatic.com/xdata/images/hotel/max500/526487640.jpg?k=b36f947fb4651f37a382cbe2c1f60dd21f4ee41a543e984953daa90650b45cd9&o=",
      "https://cf.bstatic.com/xdata/images/hotel/max500/526487612.jpg?k=1d3a19d9245ac2ec4f499ec72a9a1ce8cef571fb62f26910682e9019d9203faa&o=",
    ],
    amenities: ["WiFi", "Gratis Parkering", "Fjellutsikt", "Hage", "Terrasse", "Kjøkken", "TV", "Vaskemaskin", "Familievennlig", "Vintersport"],
    available: true,
  },

  // === NORGES-FERIE.NO PROPERTIES - KÅFJORD HYTTEGREND ===
  {
    id: "kafjord-001",
    name: "Kåfjord 001 - 9 pers",
    description: "Fantastisk beliggende hytte i Kåfjord, Lindesnes Kommune med utsikt til fjord og sjø. En flott terrasse foran hytta. Båtplass tilgjengelig. Parkering direkte ved hytta. En fantastisk plass med strand, fiskemuligheter og nydelig natur.",
    location: "Kåfjord, Lindesnes",
    beds: 5,
    bathrooms: 1,
    maxGuests: 9,
    pricePerNight: 0,
    images: [
      "http://www.norges-ferie.no/upload/images/kafjord_001/kaafjord_001.jpg",
    ],
    amenities: ["Sjøutsikt", "Terrasse", "Båtplass", "Gratis Parkering", "Kjøkken", "TV", "Strand"],
    available: true,
    externalUrl: "https://www.norges-ferie.no/lind-001-9-pers",
  },
  {
    id: "kafjord-003",
    name: "Kåfjord 003 - 10 pers",
    description: "Fantastisk beliggende hytte i Kåfjord, Lindesnes Kommune med utsikt til fjord og sjø. En kjempeterrasse foran hytta. Båtplass tilgjengelig. Høy standard med moderne fasiliteter.",
    location: "Kåfjord, Lindesnes",
    beds: 5,
    bathrooms: 1,
    maxGuests: 10,
    pricePerNight: 0,
    images: [
      "http://www.norges-ferie.no/upload/images/kafjord_003/kaafjord%2003%20hytte.jpg",
    ],
    amenities: ["Sjøutsikt", "Terrasse", "Båtplass", "Gratis Parkering", "Kjøkken", "TV", "WiFi"],
    available: true,
    externalUrl: "https://www.norges-ferie.no/kafjord-003-6-pers",
  },
  {
    id: "kafjord-004",
    name: "Kåfjord 004 - 7 pers",
    description: "Fantastisk flott hytte i Kåfjord, Lindesnes Kommune med utsikt til fjord og sjø. En kjempeterrasse foran hytta. Båtutleie tilgjengelig. Perfekt for familier som elsker friluftsliv.",
    location: "Kåfjord, Lindesnes",
    beds: 4,
    bathrooms: 1,
    maxGuests: 7,
    pricePerNight: 0,
    images: [
      "http://www.norges-ferie.no/upload/images/kaafjord_004/kaafjord%20004%2011.jpg",
    ],
    amenities: ["Sjøutsikt", "Terrasse", "Båtutleie", "Gratis Parkering", "Kjøkken", "TV"],
    available: true,
    externalUrl: "https://www.norges-ferie.no/lind-004-7-pers",
  },
  {
    id: "kafjord-005",
    name: "Kåfjord 005 - 8 pers",
    description: "Fantastisk beliggende hytte i Kåfjord, Lindesnes Kommune med nydelig direkte utsikt til fjord og sjø. En kjempeterrasse foran hytta med fantastisk solgang. Moderne innredning og høy standard.",
    location: "Kåfjord, Lindesnes",
    beds: 4,
    bathrooms: 1,
    maxGuests: 8,
    pricePerNight: 0,
    images: [
      "http://www.norges-ferie.no/upload/images/kaafjord_005/kaafjord%20005%20terrasse%20spisebord.jpg",
    ],
    amenities: ["Sjøutsikt", "Terrasse", "Gratis Parkering", "Kjøkken", "TV", "WiFi"],
    available: true,
    externalUrl: "https://www.norges-ferie.no/lind-061-8-pers",
  },
  {
    id: "kafjord-007",
    name: "Kåfjord 007 - 8 pers",
    description: "Ny (2018) og fantastisk hytte i Kåfjord, Lindesnes Kommune med stor terrasse foran og flott utsikt. Moderne innredning med høy kvalitet. Perfekt for en avslappende ferie ved sjøen.",
    location: "Kåfjord, Lindesnes",
    beds: 4,
    bathrooms: 1,
    maxGuests: 8,
    pricePerNight: 0,
    images: [
      "http://www.norges-ferie.no/upload/images/kaafjord_007/kaafjord%20007%20a%20hovedbilde.jpg",
    ],
    amenities: ["Sjøutsikt", "Terrasse", "Gratis Parkering", "Kjøkken", "TV", "WiFi", "Moderne"],
    available: true,
    externalUrl: "https://www.norges-ferie.no/kafjord-007-8-pers",
  },
  {
    id: "kafjord-008",
    name: "Kåfjord 008 - 4-6 pers",
    description: "Nydelig hytte på Kåfjord, 90m2 grunnflate. Nyere og godt utstyrt hytte med flott uteområde på solrik tomt med fantastisk uhindret sjøutsikt! Idyllisk beliggenhet med kort vei til strand og aktiviteter.",
    location: "Kåfjord, Lindesnes",
    beds: 3,
    bathrooms: 1,
    maxGuests: 6,
    pricePerNight: 0,
    images: [
      "http://www.norges-ferie.no/upload/images/kaafjord_008_new/kaafjord_008_hytte.jpg",
    ],
    amenities: ["Sjøutsikt", "Solrik", "Gratis Parkering", "Kjøkken", "TV", "WiFi"],
    available: true,
    externalUrl: "https://www.norges-ferie.no/kafjord-008-8-pers",
  },
  {
    id: "kafjord-011",
    name: "Kåfjord 011 - 10 pers",
    description: "Fantastisk beliggende hytte i Kåfjord, Lindesnes Kommune med utsikt til fjord og sjø. En kjempeterrasse foran hytta. Båtplass ca 100 meter. Parkering direkte ved hytta. En fantastisk plass med strand og fiskemuligheter.",
    location: "Kåfjord, Lindesnes",
    beds: 5,
    bathrooms: 2,
    maxGuests: 10,
    pricePerNight: 0,
    images: [
      "http://www.norges-ferie.no/upload/images/kafjord_01/ute%201.jpg",
    ],
    amenities: ["Sjøutsikt", "Terrasse", "Båtplass", "Gratis Parkering", "Kjøkken", "TV", "Strand"],
    available: true,
    externalUrl: "https://www.norges-ferie.no/kafjord-011-10-personer",
  },
  {
    id: "kafjord-012",
    name: "Kåfjord 012 - 9 pers",
    description: "Fantastisk beliggende hytte i Kåfjord, Lindesnes Kommune med utsikt over fjord og sjø. Stor terrasse med flott utsikt. Båtplass i 75 m. Parkering direkte ved hytta. Perfekt for familier og venner.",
    location: "Kåfjord, Lindesnes",
    beds: 5,
    bathrooms: 1,
    maxGuests: 9,
    pricePerNight: 0,
    images: [
      "http://www.norges-ferie.no/upload/images/kaafjord_012/kaafjord%20012%208.jpg",
    ],
    amenities: ["Sjøutsikt", "Terrasse", "Båtplass", "Gratis Parkering", "Kjøkken", "TV"],
    available: true,
    externalUrl: "https://www.norges-ferie.no/kafjord-012-9-pers",
  },

  // === FURUHOLMEN FERIESENTER ===
  {
    id: "furuholmen-panorama",
    name: "Furuholmen Panorama - 8-10 pers",
    description: "Våre største og mest innholdsrike feriehus på Furuholmen. Fantastisk utsikt mot fjord og hav. 4 soverom + hems. Bilfritt miljø gjennom parkering i garasjeanlegg. Vakker skjærgård, strender og svaberg.",
    location: "Furuholmen, Lindesnes",
    beds: 5,
    bathrooms: 2,
    maxGuests: 10,
    pricePerNight: 0,
    images: [
      "http://www.norges-ferie.no/upload/images/Furuholmen%20Panorama%2059/Furuholmen%2005.10.09%20022%20(Medium).jpg",
    ],
    amenities: ["Sjøutsikt", "Strand", "Båtutleie", "Gratis Parkering", "Kjøkken", "TV", "WiFi", "Lekeplass", "Bilfritt"],
    available: true,
    externalUrl: "https://www.norges-ferie.no/Furuholmen-Panorama",
  },
  {
    id: "furuholmen-typ-a",
    name: "Furuholmen Type A - 6-8 pers",
    description: "Store feriehus på Furuholmen, ca 74 m2 over 2-3 etasjer med 4 soverom. Bad med dusj/wc, vaskemaskin, stue med TV, innholdsrikt kjøkken med oppvaskmaskin. Fantastisk havutsikt og direkte adgang til sjøen.",
    location: "Furuholmen, Lindesnes",
    beds: 4,
    bathrooms: 1,
    maxGuests: 8,
    pricePerNight: 0,
    images: [
      "http://www.norges-ferie.no/upload/images/furuholmen/furuholmen%20eksteri%C3%B8r/oversikt%20mot%20typ%20a.jpg",
    ],
    amenities: ["Sjøutsikt", "Strand", "Vaskemaskin", "Oppvaskmaskin", "Kjøkken", "TV", "WiFi", "Bilfritt"],
    available: true,
    externalUrl: "https://www.norges-ferie.no/furuholmen-typ-a",
  },
  {
    id: "furuholmen-typ-b",
    name: "Furuholmen Type B - 6 pers",
    description: "Feriehus på Furuholmen lik type C, men ligger ikke direkte ved vannet. 3 soverom med god plass. Fullt utstyrt kjøkken, vaskemaskin og TV. Bilfritt miljø gjennom innendørs parkering.",
    location: "Furuholmen, Lindesnes",
    beds: 3,
    bathrooms: 1,
    maxGuests: 6,
    pricePerNight: 0,
    images: [
      "http://www.norges-ferie.no/upload/images/Furuholmen/Furuholmen%20eksteri%C3%B8r/Overikt%20gate%20mellom%20A%20og%20D.jpg",
    ],
    amenities: ["Strand", "Vaskemaskin", "Kjøkken", "TV", "WiFi", "Lekeplass", "Bilfritt"],
    available: true,
    externalUrl: "https://www.norges-ferie.no/Furuholmen-Typ-B",
  },
  {
    id: "furuholmen-typ-c",
    name: "Furuholmen Type C - 6 pers",
    description: "Store feriehus på Furuholmen, ca 74 m2 over 2 etasjer med 3 soverom. Bad med dusj/wc, vaskemaskin, stue med TV og internett. Fantastisk havutsikt og direkte ved sjøen.",
    location: "Furuholmen, Lindesnes",
    beds: 3,
    bathrooms: 1,
    maxGuests: 6,
    pricePerNight: 0,
    images: [
      "http://www.norges-ferie.no/upload/images/Furuholmen/Furuholmen%20bannerbilder/Furuholmen-640-banner-II.jpg",
    ],
    amenities: ["Sjøutsikt", "Strand", "Vaskemaskin", "Oppvaskmaskin", "Kjøkken", "TV", "WiFi", "Bilfritt"],
    available: true,
    externalUrl: "https://www.norges-ferie.no/Furuholmen-Typ-C",
  },
  {
    id: "furuholmen-typ-d",
    name: "Furuholmen Type D - 6-8 pers",
    description: "Store feriehus på Furuholmen lik innredning som type C. Begrenset havutsikt, men nærhet til sjøen. 3 soverom og 2 WC. Bilfritt miljø gjennom parkering under bakken.",
    location: "Furuholmen, Lindesnes",
    beds: 3,
    bathrooms: 2,
    maxGuests: 8,
    pricePerNight: 0,
    images: [
      "http://www.norges-ferie.no/upload/images/Furuholmen/Div.%20bilder%20Furuholmen/Furuholmen-640-Banner-III.jpg",
    ],
    amenities: ["Strand", "Vaskemaskin", "Kjøkken", "TV", "WiFi", "2 Bad", "Bilfritt"],
    available: true,
    externalUrl: "https://www.norges-ferie.no/Furuholmen-Typ-D",
  },

  // === MONESSTRANDA MANDAL ===
  {
    id: "monesstranda-mandal",
    name: "Monesstranda ved Mandal A07",
    description: "Komfortabel feriebolig på Monesstranda med to soverom og ett bad. Gjester nyter gratis WiFi, balkong med hageutsikt, fullt utstyrt kjøkken og vaskemaskin. Lindesnes fyr er 37 km unna.",
    location: "Rugland, Mandal",
    beds: 3,
    bathrooms: 1,
    maxGuests: 6,
    pricePerNight: 0,
    images: [
      "https://cf.bstatic.com/xdata/images/hotel/max1024x768/736507024.jpg?k=cc4d042ddeea5b0dd49f8782847cd156f68c848ade5c098ad49f02da291f0bab&o=",
      "https://cf.bstatic.com/xdata/images/hotel/max500/736507018.jpg?k=e0d54d15f75469aaf83b94535260bf126b5195cd53866113ee3367fcf7fd2549&o=",
    ],
    amenities: ["WiFi", "Gratis Parkering", "Balkong", "Kjøkken", "TV", "Vaskemaskin", "Kjæledyr Tillatt"],
    available: true,
    externalUrl: "https://www.norges-ferie.no/monesstranda-typ-a07",
  },
  {
    id: "monesstranda-typ-b01",
    name: "Monesstranda Type B01 - 7 pers",
    description: "Leilighet på Mones, det nyeste feriesenter i Mandalsområdet. Flotte, smakfulle leiligheter, direkte ved Skogsfjorden. Kort avstand til Mandal by. 3 soverom over 2 etasjer med 2 bad.",
    location: "Monesstranda, Mandal",
    beds: 4,
    bathrooms: 2,
    maxGuests: 7,
    pricePerNight: 0,
    images: [
      "http://www.norges-ferie.no/upload/images/monesstranda_1b_new/monesstanda%201b.jpg",
    ],
    amenities: ["Sjøutsikt", "Balkong", "Vaskemaskin", "Kjøkken", "TV", "WiFi", "2 Bad", "Lekeplass"],
    available: true,
    externalUrl: "https://www.norges-ferie.no/monesstranda-typ-b01",
  },
  {
    id: "monesstranda-typ-c",
    name: "Monesstranda Type C - 5 pers",
    description: "Leiligheter på ca 55m2 med 1 etasje. 4-5 sengeplasser fordelt på 2 soverom. Stue, bad med dusj/wc, vaskemaskin, fullt utstyrt kjøkken og terrasse. Direkte ved vannet.",
    location: "Monesstranda, Mandal",
    beds: 2,
    bathrooms: 1,
    maxGuests: 5,
    pricePerNight: 0,
    images: [
      "http://www.norges-ferie.no/upload/images/monesstranda/monesstranda%20bannerbilder/bilder%20alle%20feriesenter%20041.jpg",
    ],
    amenities: ["Sjøutsikt", "Terrasse", "Vaskemaskin", "Kjøkken", "TV", "WiFi", "Strand"],
    available: true,
    externalUrl: "https://www.norges-ferie.no/monesstranda-typ-c09",
  },

  // === ÅVIK BRYGGE ===
  {
    id: "avik-type-a22",
    name: "Åvik Type A22 - 6 pers",
    description: "Nyrenovert flott 50 kvm stor leilighet med utsikt vestover. Balkong mot vest og utsikt utover sjøen med masse ettermiddags og kveldsol. Stue/kjøkken, bad med dusj og toalett samt 2 soverom.",
    location: "Åvik Brygge, Lindesnes",
    beds: 3,
    bathrooms: 1,
    maxGuests: 6,
    pricePerNight: 0,
    images: [
      "http://www.norges-ferie.no/upload/images/aavik_22_new/aavik%2022%2015_easy-resize.com.jpg",
    ],
    amenities: ["Sjøutsikt", "Balkong", "Fiskerom", "Båtutleie", "Kjøkken", "TV", "WiFi"],
    available: true,
    externalUrl: "https://www.norges-ferie.no/avik-typea22",
  },
  {
    id: "avik-type-a14",
    name: "Åvik Type A14 - 6 pers",
    description: "50 kvm stor leilighet med fantastisk beliggenhet kun 2 meter fra bryggen og båtplassene. Terrasse mot bukten og den gamle bebyggelsen i Åvik. Stue/kjøkken, bad med dusj og toalett samt 2 soverom.",
    location: "Åvik Brygge, Lindesnes",
    beds: 3,
    bathrooms: 1,
    maxGuests: 6,
    pricePerNight: 0,
    images: [
      "http://www.norges-ferie.no/upload/images/avik_14_ny/aavik%2014%2010_easy-resize.com.jpg",
    ],
    amenities: ["Sjøutsikt", "Terrasse", "Båtplass", "Fiskerom", "Kjøkken", "TV", "WiFi"],
    available: true,
    externalUrl: "https://www.norges-ferie.no/avik-typea14",
  },
  {
    id: "avik-type-a32",
    name: "Åvik Type A32 - 6 pers",
    description: "Leilighet i 3. etg. med kjempestor egen terrasse på neste 50 kvm. Utsikt i alle retninger. Sol fra morgen til kveld. 50 kvm med stue/kjøkken, bad/dusj samt to soverom.",
    location: "Åvik Brygge, Lindesnes",
    beds: 3,
    bathrooms: 1,
    maxGuests: 6,
    pricePerNight: 0,
    images: [
      "http://www.norges-ferie.no/upload/images/%C3%85vik32A/01%20(Small).JPG",
    ],
    amenities: ["Panoramautsikt", "Stor Terrasse", "Fiskerom", "Båtutleie", "Kjøkken", "TV", "WiFi"],
    available: true,
    externalUrl: "https://www.norges-ferie.no/avik-typea32",
  },
  {
    id: "avik-type-a33",
    name: "Åvik Type A33 - 6 pers",
    description: "Den største leiligheten på Åvik Brygge, med utsikt både til bukt og ut over havet. 2 store solrike terrasser med direkte utgang fra stue, gir store muligheter til både kos og grilling.",
    location: "Åvik Brygge, Lindesnes",
    beds: 3,
    bathrooms: 1,
    maxGuests: 6,
    pricePerNight: 0,
    images: [
      "http://www.norges-ferie.no/upload/images/a_32_ny/20231008_123858.jpg",
    ],
    amenities: ["Sjøutsikt", "2 Terrasser", "Grill", "Fiskerom", "Båtutleie", "Kjøkken", "TV", "WiFi"],
    available: true,
    externalUrl: "https://www.norges-ferie.no/avik-typea33",
  },
  {
    id: "avik-type-c23",
    name: "Åvik Type C23 - 2 pers",
    description: "Koselig ca 35 kvm stor leilighet med utsikt mot vest, havet og skipsleia. Masse kveldssol og utsikt fra egen terrasse. 1 soverom med plass for 2. Fullt utstyrt kjøkkenhørne.",
    location: "Åvik Brygge, Lindesnes",
    beds: 1,
    bathrooms: 1,
    maxGuests: 2,
    pricePerNight: 0,
    images: [
      "http://www.norges-ferie.no/upload/images/%C3%A5v.w23/aavik%2023%2016_easy-resize.com.jpg",
    ],
    amenities: ["Sjøutsikt", "Terrasse", "Fiskerom", "Båtutleie", "Kjøkken", "TV", "WiFi"],
    available: true,
    externalUrl: "https://www.norges-ferie.no/avik-typec23",
  },

  // === LIND PROPERTIES ===
  {
    id: "lind-004",
    name: "Lind 004 - 6 pers",
    description: "Flotte leilighet i Åvik/Lindesnes kommune helt ytterst ved havet i naturskjønne omgivelser. Koselig innredet og meget godt utstyrt. Kjøkken med komfyr, stekeovn, kjøleskap og oppvaskmaskin.",
    location: "Åvik, Lindesnes",
    beds: 3,
    bathrooms: 1,
    maxGuests: 6,
    pricePerNight: 0,
    images: [
      "http://www.norges-ferie.no/upload/images/lind_004_ny/lind%20004%201.jpeg",
    ],
    amenities: ["Sjøutsikt", "Kjøkken", "Oppvaskmaskin", "TV", "WiFi"],
    available: true,
    externalUrl: "https://www.norges-ferie.no/lind-004-6-pers",
  },
  {
    id: "lind-006",
    name: "Lind 006 - 10 pers",
    description: "Flott hytte på Urvikodden i Lindesnes kommune. Helt ytterst i havgapet med nydelig utsikt mot sjøen. Koselig innredet og meget godt utstyrt. Hytten har også 2 terrasser.",
    location: "Urvikodden, Lindesnes",
    beds: 5,
    bathrooms: 1,
    maxGuests: 10,
    pricePerNight: 0,
    images: [
      "http://www.norges-ferie.no/upload/images/lind_006_new/lind_006a.jpg",
    ],
    amenities: ["Sjøutsikt", "2 Terrasser", "Kjøkken", "TV", "WiFi", "Havgap"],
    available: true,
    externalUrl: "https://www.norges-ferie.no/lind-006-8-pers",
  },
  {
    id: "lind-009",
    name: "Lind 009 - 4 pers",
    description: "2 soverom. Et soverom med dobbelseng og et med 2 enkle senger. Separat kjøkken med el. komfyr, kjøleskap/fryser, kaffetrakter, vannkoker, oppvaskmaskin og vaskemaskin.",
    location: "Lindesnes",
    beds: 2,
    bathrooms: 1,
    maxGuests: 4,
    pricePerNight: 0,
    images: [
      "http://www.norges-ferie.no/upload/images/lind_009_new/img_4705.jpg",
    ],
    amenities: ["Kjøkken", "Oppvaskmaskin", "Vaskemaskin", "TV", "WiFi"],
    available: true,
    externalUrl: "https://www.norges-ferie.no/lind-009-6-pers",
  },
  {
    id: "lind-013",
    name: "Lind 013 - 6 pers",
    description: "Koselig eldre hus i Åvik/Lindesnes som er ny-renovert i 2021. Nymalt og velholdt. Huset er godt ivaretatt. Idyllisk beliggenhet med utsikt over Øverstranda.",
    location: "Åvik, Lindesnes",
    beds: 3,
    bathrooms: 1,
    maxGuests: 6,
    pricePerNight: 0,
    images: [
      "http://www.norges-ferie.no/upload/images/lind_013_ny/lind%20013%20001.jpg",
    ],
    amenities: ["Sjøutsikt", "Renovert", "Kjøkken", "TV", "WiFi", "Idyllisk"],
    available: true,
    externalUrl: "https://www.norges-ferie.no/lind-013",
  },
  {
    id: "lind-060",
    name: "Lind 060 - 4 pers",
    description: "Flott hytte på Urvikodden/Lindesnes helt ytterst i havgapet. Koselig innredet og meget godt utstyrt. Stue med TV/Parabol. Kjøkken med v/k vann, komfyr, kjøleskap.",
    location: "Urvikodden, Lindesnes",
    beds: 2,
    bathrooms: 1,
    maxGuests: 4,
    pricePerNight: 0,
    images: [
      "http://www.norges-ferie.no/upload/images/Lind060/hervold%20006%20(Medium).jpg",
    ],
    amenities: ["Sjøutsikt", "Havgap", "Kjøkken", "TV", "Parabol"],
    available: true,
    externalUrl: "https://www.norges-ferie.no/lind-060-4-pers",
  },
  {
    id: "lind-072",
    name: "Lind 072 - 6 pers",
    description: "Flott hytte ved Båly Brygge, Spangereid langs vannkanten ved Spangereidkanalen. På et lite nes ut mot havet. Området er anlagt som en hyggelig uthavn med båtutleie.",
    location: "Spangereid, Lindesnes",
    beds: 3,
    bathrooms: 1,
    maxGuests: 6,
    pricePerNight: 0,
    images: [
      "http://www.norges-ferie.no/upload/images/lind_072/baaly%20072.jpg",
    ],
    amenities: ["Sjøutsikt", "Båtutleie", "Vannkant", "Kjøkken", "TV", "WiFi"],
    available: true,
    externalUrl: "https://www.norges-ferie.no/lind-072-5-6",
  },
  {
    id: "lind-085",
    name: "Lind 085 - 6 pers",
    description: "Hus i Åvik/Lindesnes ca 250 m fra Åvik Brygge. Fra huset kan en se den idylliske skjærgården og den lille Sørlandsperlen Svinør. Sol fra tidlig morgen til sen kveld.",
    location: "Åvik, Lindesnes",
    beds: 3,
    bathrooms: 1,
    maxGuests: 6,
    pricePerNight: 0,
    images: [
      "http://www.norges-ferie.no/upload/images/lind_085_new/lind%20085%203.jpg",
    ],
    amenities: ["Skjærgård", "Solrikt", "Kjøkken", "TV", "WiFi", "Nær Brygge"],
    available: true,
    externalUrl: "https://www.norges-ferie.no/lind-085-6-pers",
  },

  // === SPAIN PROPERTIES - HOLIDAYSINSPAIN4U.COM ===
  {
    id: "spain-la-zenia-3bed",
    name: "La Zenia 3 Bed Apartment",
    description: "Spacious 3 bedroom apartment in La Zenia with 2 bathrooms. 100 sqm of living space with pool access. Perfect for families or groups looking for a comfortable holiday base on the Costa Blanca.",
    location: "La Zenia, Costa Blanca, Spain",
    beds: 3,
    bathrooms: 2,
    maxGuests: 6,
    pricePerNight: 63,
    images: [
      "https://www.holidaysinspain4u.com/images/osproperty/properties/1063/medium/10631579963534poolandsurrounds.JPG",
    ],
    amenities: ["Pool", "WiFi", "Air Conditioning", "Terrace", "Kitchen", "TV", "Parking"],
    available: true,
    externalUrl: "https://www.holidaysinspain4u.com/index.php/properties-for-rent/u1-la-zenia-3-bed-apartment-1063",
  },
  {
    id: "spain-cabo-roig-townhouse",
    name: "Cabo Roig 2 Bed Townhouse",
    description: "Charming 2 bedroom townhouse in Cabo Roig with 1.5 bathrooms. 80 sqm of space with private terrace. Great location near beaches and restaurants on the Orihuela Costa.",
    location: "Cabo Roig, Costa Blanca, Spain",
    beds: 2,
    bathrooms: 2,
    maxGuests: 4,
    pricePerNight: 45,
    images: [
      "https://www.holidaysinspain4u.com/images/osproperty/properties/1011/medium/10111581165936Frontage.JPG",
    ],
    amenities: ["Pool", "WiFi", "Air Conditioning", "Terrace", "Kitchen", "TV", "Parking"],
    available: true,
    externalUrl: "https://www.holidaysinspain4u.com/index.php/properties-for-rent/i4-14-cabo-roig-2-bed-house-1011",
  },
  {
    id: "spain-cabo-roig-atico",
    name: "Cabo Roig Strip 2 Bed Atico Apartment",
    description: "Stylish 2 bedroom penthouse apartment on the Cabo Roig strip with 1 bathroom. 70 sqm with rooftop solarium. Walking distance to beach, shops and restaurants.",
    location: "Cabo Roig, Costa Blanca, Spain",
    beds: 2,
    bathrooms: 1,
    maxGuests: 4,
    pricePerNight: 45,
    images: [
      "https://www.holidaysinspain4u.com/images/osproperty/properties/1017/medium/1017_ea_imgp72581.jpg",
    ],
    amenities: ["Pool", "WiFi", "Solarium", "Kitchen", "TV", "Near Beach"],
    available: true,
    externalUrl: "https://www.holidaysinspain4u.com/index.php/properties-for-rent/r2-20-cabo-roig-strip-2-bed-atico-apartment-1017",
  },
  {
    id: "spain-cabo-roig-strip-apt",
    name: "Cabo Roig Strip 2 Bed Apartment",
    description: "Comfortable 2 bedroom apartment on the Cabo Roig strip with 1 bathroom. 70 sqm in a great location for beach holidays. Close to all amenities and the famous Saturday market.",
    location: "Cabo Roig, Costa Blanca, Spain",
    beds: 2,
    bathrooms: 1,
    maxGuests: 4,
    pricePerNight: 45,
    images: [
      "https://www.holidaysinspain4u.com/images/osproperty/properties/1018/medium/1018_ea_costamarina_504223123.jpg",
    ],
    amenities: ["Pool", "WiFi", "Air Conditioning", "Terrace", "Kitchen", "TV"],
    available: true,
    externalUrl: "https://www.holidaysinspain4u.com/index.php/properties-for-rent/s1-21-cabo-roig-strip-2-bed-apartment-1018",
  },
  {
    id: "spain-cabo-roig-3bed-house",
    name: "Cabo Roig 3 Bed House",
    description: "Spacious 3 bedroom house in Cabo Roig with 2 bathrooms. 120 sqm of living space with private garden. Perfect family holiday home on the Costa Blanca.",
    location: "Cabo Roig, Costa Blanca, Spain",
    beds: 3,
    bathrooms: 2,
    maxGuests: 6,
    pricePerNight: 54,
    images: [
      "https://www.holidaysinspain4u.com/images/osproperty/properties/1021/medium/1021_ea_cabo_roig_holiday_home_in_spain_costa_blanca__110___800x600_.jpg",
    ],
    amenities: ["Pool", "WiFi", "Air Conditioning", "Garden", "Kitchen", "TV", "Parking"],
    available: true,
    externalUrl: "https://www.holidaysinspain4u.com/index.php/properties-for-rent/v1-88-cabo-roig-3-bed-house-1021",
  },
  {
    id: "spain-cabo-roig-quad",
    name: "Cabo Roig 3 Bed Quad House",
    description: "Beautiful 3 bedroom quad house in Cabo Roig with 2 bathrooms. 150 sqm with communal pool and private parking. Ideal for families seeking Spanish sunshine.",
    location: "Cabo Roig, Costa Blanca, Spain",
    beds: 3,
    bathrooms: 2,
    maxGuests: 6,
    pricePerNight: 54,
    images: [
      "https://www.holidaysinspain4u.com/images/osproperty/properties/1029/medium/1029_ea_apr_2013_058__800x600__jpg.jpg",
    ],
    amenities: ["Pool", "WiFi", "Air Conditioning", "Terrace", "Kitchen", "TV", "Parking"],
    available: true,
    externalUrl: "https://www.holidaysinspain4u.com/index.php/properties-for-rent/f1-78-cabo-roig-3-bed-quad-house-1029",
  },
  {
    id: "spain-cabo-roig-frontline",
    name: "Cabo Roig 2 Bed Frontline Apartment",
    description: "Stunning 2 bedroom frontline apartment in Cabo Roig with 2 bathrooms. 75 sqm with beautiful sea views. Direct access to the beach and promenade.",
    location: "Cabo Roig, Costa Blanca, Spain",
    beds: 2,
    bathrooms: 2,
    maxGuests: 4,
    pricePerNight: 55,
    images: [
      "https://www.holidaysinspain4u.com/images/osproperty/properties/1059/medium/10591542126445MarinasolPool.jpg",
    ],
    amenities: ["Pool", "WiFi", "Sea View", "Beachfront", "Kitchen", "TV"],
    available: true,
    externalUrl: "https://www.holidaysinspain4u.com/index.php/properties-for-rent/d2-cabo-roig-2-bed-frontline-apartment-1059",
  },
  {
    id: "spain-la-zenia-luxury",
    name: "Cabo Roig / La Zenia 2 Bed Luxurious Apartment",
    description: "Luxurious 2 bedroom apartment between Cabo Roig and La Zenia with 1 bathroom. 90 sqm of elegantly furnished space. Close to Zenia Boulevard shopping center.",
    location: "La Zenia, Costa Blanca, Spain",
    beds: 2,
    bathrooms: 1,
    maxGuests: 4,
    pricePerNight: 60,
    images: [
      "https://www.holidaysinspain4u.com/images/osproperty/properties/1032/medium/1032_1_cover.jpg",
    ],
    amenities: ["Pool", "WiFi", "Air Conditioning", "Luxury", "Kitchen", "TV", "Near Shopping"],
    available: true,
    externalUrl: "https://www.holidaysinspain4u.com/index.php/properties-for-rent/q1-82-cabo-roig-la-zenia-luxurious-apartment-1032",
  },
  {
    id: "spain-villamartin-pool",
    name: "Villamartin 2 Bed House with Private Pool",
    description: "Fantastic 2 bedroom house in Villamartin with 1.5 bathrooms and private pool. 120 sqm with beautiful garden. Near golf courses and Zenia Boulevard.",
    location: "Villamartin, Costa Blanca, Spain",
    beds: 2,
    bathrooms: 2,
    maxGuests: 4,
    pricePerNight: 69,
    images: [
      "https://www.holidaysinspain4u.com/images/osproperty/properties/1041/medium/1041_ea_p2_frontage.jpg",
    ],
    amenities: ["Private Pool", "WiFi", "Air Conditioning", "Garden", "Kitchen", "TV", "Golf Nearby"],
    available: true,
    externalUrl: "https://www.holidaysinspain4u.com/index.php/properties-for-rent/p2-117-villamartin-2-bed-house-with-private-pool-1041",
  },
  {
    id: "spain-la-zenia-penthouse",
    name: "La Zenia 2 Bed Penthouse Apartment",
    description: "Lovely 2 bedroom penthouse in La Zenia with 1 bathroom and solarium. 100 sqm including rooftop terrace. Perfect for sun lovers seeking Spanish holiday.",
    location: "La Zenia, Costa Blanca, Spain",
    beds: 2,
    bathrooms: 1,
    maxGuests: 4,
    pricePerNight: 51,
    images: [
      "https://www.holidaysinspain4u.com/images/osproperty/properties/1043/medium/1043_ea_2_bed_apartment_for_rent_la_zenia_1_.jpg",
    ],
    amenities: ["Pool", "WiFi", "Solarium", "Terrace", "Kitchen", "TV"],
    available: true,
    externalUrl: "https://www.holidaysinspain4u.com/index.php/properties-for-rent/b2-97-la-zenia-2-bed-penthouse-with-solarium-for-rent-1043",
  },
  {
    id: "spain-la-zenia-private-pool",
    name: "La Zenia 2 Bed with Private Pool",
    description: "Beautiful 2 bedroom property in La Zenia with 2 bathrooms and private pool. 90 sqm of modern living space. Perfect for couples or small families.",
    location: "La Zenia, Costa Blanca, Spain",
    beds: 2,
    bathrooms: 2,
    maxGuests: 4,
    pricePerNight: 69,
    images: [
      "https://www.holidaysinspain4u.com/images/osproperty/properties/1053/medium/10531512035517IMG_0806.JPG",
    ],
    amenities: ["Private Pool", "WiFi", "Air Conditioning", "Terrace", "Kitchen", "TV"],
    available: true,
    externalUrl: "https://www.holidaysinspain4u.com/index.php/properties-for-rent/l2-la-zenia-2-bed-with-private-pool-1053",
  },
  {
    id: "spain-cabo-roig-quad-c4",
    name: "Cabo Roig 2 Bed Quad House",
    description: "Charming 2 bedroom quad house in Cabo Roig with 2 bathrooms. Communal pool and well-maintained garden area. Great value for Costa Blanca holidays.",
    location: "Cabo Roig, Costa Blanca, Spain",
    beds: 2,
    bathrooms: 2,
    maxGuests: 4,
    pricePerNight: 65,
    images: [
      "https://www.holidaysinspain4u.com/images/osproperty/properties/1067/medium/10671643197141IMG_8828.jpg",
    ],
    amenities: ["Pool", "WiFi", "Air Conditioning", "Garden", "Kitchen", "TV", "Parking"],
    available: true,
    externalUrl: "https://www.holidaysinspain4u.com/index.php/properties-for-rent/c4-cabo-roig-2-bed-quad-house-1067",
  },
  {
    id: "spain-villamartin-apt",
    name: "Villamartin 2 Bed Apartment",
    description: "Comfortable 2 bedroom apartment in Villamartin with 1 bathroom. 60 sqm near golf courses and restaurants. Perfect base for exploring the Costa Blanca.",
    location: "Villamartin, Costa Blanca, Spain",
    beds: 2,
    bathrooms: 1,
    maxGuests: 4,
    pricePerNight: 60,
    images: [
      "https://www.holidaysinspain4u.com/images/osproperty/properties/1073/medium/107317092060471-Lounge1.jpg",
    ],
    amenities: ["Pool", "WiFi", "Air Conditioning", "Terrace", "Kitchen", "TV", "Golf Nearby"],
    available: true,
    externalUrl: "https://www.holidaysinspain4u.com/index.php/properties-for-rent/p3-p3-villamartin-2-bed-apartment-1073",
  },
  {
    id: "spain-cabo-roig-s3",
    name: "2 Bed Apartment, Cabo Roig",
    description: "Well-appointed 2 bedroom apartment in Cabo Roig with 1 bathroom. Community pool and great location. Ideal for beach holidays on the Costa Blanca.",
    location: "Cabo Roig, Costa Blanca, Spain",
    beds: 2,
    bathrooms: 1,
    maxGuests: 4,
    pricePerNight: 55,
    images: [
      "https://www.holidaysinspain4u.com/images/osproperty/properties/1076/medium/10761716108180frontview.jpg",
    ],
    amenities: ["Pool", "WiFi", "Air Conditioning", "Kitchen", "TV", "Near Beach"],
    available: true,
    externalUrl: "https://www.holidaysinspain4u.com/index.php/properties-for-rent/s3-2-bed-apartment-cabo-roig-1076",
  },
  {
    id: "spain-torrevieja-apt",
    name: "Torrevieja 2 Bed Apartment",
    description: "Modern 2 bedroom apartment in Torrevieja with 1 bathroom. Close to the famous salt lakes and beaches. Great value accommodation on the Costa Blanca.",
    location: "Torrevieja, Costa Blanca, Spain",
    beds: 2,
    bathrooms: 1,
    maxGuests: 4,
    pricePerNight: 60,
    images: [
      "https://www.holidaysinspain4u.com/images/osproperty/properties/1077/medium/107717178356781.jpg",
    ],
    amenities: ["Pool", "WiFi", "Air Conditioning", "Terrace", "Kitchen", "TV"],
    available: true,
    externalUrl: "https://www.holidaysinspain4u.com/index.php/properties-for-rent/t3-torrevieja-2-bed-apartment-1077",
  },
  {
    id: "spain-cabo-roig-r5",
    name: "2 Bed Apartment Cabo Roig",
    description: "Lovely 2 bedroom apartment in Cabo Roig with 1 bathroom. Communal pool and sunny terrace. Perfect holiday retreat on Spain's Costa Blanca.",
    location: "Cabo Roig, Costa Blanca, Spain",
    beds: 2,
    bathrooms: 1,
    maxGuests: 4,
    pricePerNight: 55,
    images: [
      "https://www.holidaysinspain4u.com/images/osproperty/properties/1079/medium/10791748267748IMG_4929.jpg",
    ],
    amenities: ["Pool", "WiFi", "Air Conditioning", "Terrace", "Kitchen", "TV"],
    available: true,
    externalUrl: "https://www.holidaysinspain4u.com/index.php/properties-for-rent/r5-2-bed-apartment-cabo-roig-1079-1079",
  },
  {
    id: "spain-cabo-roig-d7",
    name: "Cabo Roig 2 Bed Apartment",
    description: "Stylish 2 bedroom apartment in Cabo Roig. Modern furnishings and great community facilities. Walking distance to beaches and local amenities.",
    location: "Cabo Roig, Costa Blanca, Spain",
    beds: 2,
    bathrooms: 1,
    maxGuests: 4,
    pricePerNight: 60,
    images: [
      "https://www.holidaysinspain4u.com/images/osproperty/properties/1080/medium/10801769154514Lounge2.JPG",
    ],
    amenities: ["Pool", "WiFi", "Air Conditioning", "Kitchen", "TV", "Near Beach"],
    available: true,
    externalUrl: "https://www.holidaysinspain4u.com/index.php/properties-for-rent/d7-cabo-roig-2-bed-apartment-1080-1080",
  },
  {
    id: "spain-campoamor-3bed",
    name: "Campoamor 3 Bed Apartment",
    description: "Spacious 3 bedroom apartment in Campoamor. Perfect for families with children. Near Campoamor beach and Las Ramblas golf course.",
    location: "Campoamor, Costa Blanca, Spain",
    beds: 3,
    bathrooms: 2,
    maxGuests: 6,
    pricePerNight: 70,
    images: [
      "https://www.holidaysinspain4u.com/images/osproperty/properties/1081/medium/1081_lounge_3.jpg",
    ],
    amenities: ["Pool", "WiFi", "Air Conditioning", "Terrace", "Kitchen", "TV", "Near Golf"],
    available: true,
    externalUrl: "https://www.holidaysinspain4u.com/index.php/properties-for-rent/d8-3bed-apartment-campoamor-1081",
  },
  {
    id: "spain-cabo-roig-h3-quad",
    name: "Cabo Roig 3 Bed Quad House",
    description: "Well-maintained 3 bedroom quad house in Cabo Roig with 2 bathrooms. Communal pool and nice outdoor space. Great family holiday home.",
    location: "Cabo Roig, Costa Blanca, Spain",
    beds: 3,
    bathrooms: 2,
    maxGuests: 6,
    pricePerNight: 63,
    images: [
      "https://www.holidaysinspain4u.com/images/osproperty/properties/1072/medium/1072_front_of_house_-_cover_photo.jpg",
    ],
    amenities: ["Pool", "WiFi", "Air Conditioning", "Garden", "Kitchen", "TV", "Parking"],
    available: true,
    externalUrl: "https://www.holidaysinspain4u.com/index.php/properties-for-rent/h3-cabo-roig-3-bed-quad-house-1072",
  },

  // === FURREHYTTER - SJERNARØY ISLAND CABINS ===
  {
    id: "furrehytter-h1",
    name: "Furrehytter Hytte 1",
    description: "En av våre mest populære hytter, bygget i sjøhusstil like på bryggekanten. Hytten er velutstyrt og du kan boltre deg på to etasjer. Perfekt for fiske- og familieferie på Sjernarøy.",
    location: "Sjernarøy, Stavanger",
    beds: 3,
    bathrooms: 1,
    maxGuests: 8,
    pricePerNight: 0,
    images: [
      "https://usercontent.one/wp/furrehytter.no/wp-content/uploads/2025/05/hytte-1-scaled.jpg",
      "https://usercontent.one/wp/furrehytter.no/wp-content/uploads/2025/05/H1_Peis.jpeg",
      "https://usercontent.one/wp/furrehytter.no/wp-content/uploads/2025/05/H1_Bad.jpeg",
      "https://usercontent.one/wp/furrehytter.no/wp-content/uploads/2025/05/hytte-nr1-stor3.jpg",
      "https://usercontent.one/wp/furrehytter.no/wp-content/uploads/2025/05/hytte-nr1-stor2.jpg",
    ],
    amenities: ["Sjøutsikt", "Bryggekant", "Peis", "Gulvvarme", "Kjøkken", "TV", "WiFi", "Chromecast"],
    available: true,
    externalUrl: "https://furrehytter.no/hytter/h1",
  },
  {
    id: "furrehytter-h2",
    name: "Furrehytter Hytte 2",
    description: "1. etasje av velutstyrt hytte i sjøhusstil med alle fasiliteter. Hytten ligger vegg i vegg med hytte nr. 1 og har super beliggenhet på bryggekanten.",
    location: "Sjernarøy, Stavanger",
    beds: 2,
    bathrooms: 1,
    maxGuests: 6,
    pricePerNight: 0,
    images: [
      "https://usercontent.one/wp/furrehytter.no/wp-content/uploads/2025/05/hytte-2.jpg",
      "https://usercontent.one/wp/furrehytter.no/wp-content/uploads/2025/05/H2_Living.jpg",
      "https://usercontent.one/wp/furrehytter.no/wp-content/uploads/2025/05/H2_Dining_View.jpg",
      "https://usercontent.one/wp/furrehytter.no/wp-content/uploads/2025/05/H2_Kitchen.jpg",
    ],
    amenities: ["Sjøutsikt", "Bryggekant", "Peis", "Kjøkken", "TV", "WiFi", "Chromecast"],
    available: true,
    externalUrl: "https://furrehytter.no/hytter/h2",
  },
  {
    id: "furrehytter-h3",
    name: "Furrehytter Hytte 3",
    description: "2. etasje i hytte nr 2. Hytten ligger på bryggen, helt i sjøkanten med kort avstand til parkeringsplass. Her har du også tilgang til utegrill.",
    location: "Sjernarøy, Stavanger",
    beds: 1,
    bathrooms: 1,
    maxGuests: 4,
    pricePerNight: 0,
    images: [
      "https://usercontent.one/wp/furrehytter.no/wp-content/uploads/2025/05/hytte-3.jpg",
      "https://usercontent.one/wp/furrehytter.no/wp-content/uploads/2025/05/MG_4591_edited.jpg",
      "https://usercontent.one/wp/furrehytter.no/wp-content/uploads/2025/05/MG_4592_edited.jpg",
      "https://usercontent.one/wp/furrehytter.no/wp-content/uploads/2025/05/MG_4600_edited.jpg",
    ],
    amenities: ["Sjøutsikt", "Bryggekant", "Peis", "Grill", "Kjøkken", "TV", "WiFi"],
    available: true,
    externalUrl: "https://furrehytter.no/hytter/h3",
  },
  {
    id: "furrehytter-h4",
    name: "Furrehytter Hytte 4",
    description: "Her kan du virkelig finne roen! Hytten ligger usjenert til, litt høyere i terrenget (ca 25 meter fra sjøen), med overbygget terrasse og panoramautsikt.",
    location: "Sjernarøy, Stavanger",
    beds: 4,
    bathrooms: 2,
    maxGuests: 8,
    pricePerNight: 0,
    images: [
      "https://usercontent.one/wp/furrehytter.no/wp-content/uploads/2025/05/20150502_115507.jpg",
      "https://usercontent.one/wp/furrehytter.no/wp-content/uploads/2025/05/MG_4676_edited.jpg",
      "https://usercontent.one/wp/furrehytter.no/wp-content/uploads/2025/05/MG_4648_edited.jpg",
      "https://usercontent.one/wp/furrehytter.no/wp-content/uploads/2025/05/MG_4656_edited.jpg",
    ],
    amenities: ["Panoramautsikt", "Terrasse", "Badstu", "2 Bad", "Peis", "Kjøkken", "TV", "WiFi"],
    available: true,
    externalUrl: "https://furrehytter.no/hytter/h4",
  },
  {
    id: "furrehytter-h5",
    name: "Furrehytter Hytte 5",
    description: "Hytte nr 5 og 6 er vertikalt delt og passer utmerket for to familier som ønsker hver sin leilighet. Hytten ligger ca. 50 meter fra sjøen og du kan parkere bilen like utenfor inngangsdøren.",
    location: "Sjernarøy, Stavanger",
    beds: 2,
    bathrooms: 1,
    maxGuests: 5,
    pricePerNight: 0,
    images: [
      "https://usercontent.one/wp/furrehytter.no/wp-content/uploads/2025/05/H5_H6_Fra_Havet-scaled.jpg",
      "https://usercontent.one/wp/furrehytter.no/wp-content/uploads/2025/05/H5_Terrasse-scaled.jpg",
      "https://usercontent.one/wp/furrehytter.no/wp-content/uploads/2025/11/H5_Livingroom-scaled.jpg",
      "https://usercontent.one/wp/furrehytter.no/wp-content/uploads/2025/11/H5_Kitchen-scaled.jpg",
    ],
    amenities: ["Sjøutsikt", "Terrasse", "Peis", "Gratis Parkering", "Kjøkken", "TV", "WiFi"],
    available: true,
    externalUrl: "https://furrehytter.no/hytter/h5",
  },
  {
    id: "furrehytter-h6",
    name: "Furrehytter Hytte 6",
    description: "Velutstyrt hytte med alle fasiliteter. Hytten ligger ca. 50 meter fra sjøen og du kan parkere bilen like utenfor inngangsdøren. Fantastisk utsikt over Fårasundet fra overbygget terrasse.",
    location: "Sjernarøy, Stavanger",
    beds: 2,
    bathrooms: 1,
    maxGuests: 5,
    pricePerNight: 0,
    images: [
      "https://usercontent.one/wp/furrehytter.no/wp-content/uploads/2025/11/H6_Livingroom-scaled.jpg",
      "https://usercontent.one/wp/furrehytter.no/wp-content/uploads/2025/11/H6_Kitchen-scaled.jpg",
      "https://usercontent.one/wp/furrehytter.no/wp-content/uploads/2025/11/H6_Bedroom-scaled.jpg",
      "https://usercontent.one/wp/furrehytter.no/wp-content/uploads/2025/11/H6_Bathroom-scaled.jpg",
    ],
    amenities: ["Sjøutsikt", "Terrasse", "Peis", "Gratis Parkering", "Kjøkken", "TV", "WiFi"],
    available: true,
    externalUrl: "https://furrehytter.no/hytter/h6",
  },
  {
    id: "furrehytter-h7",
    name: "Furrehytter Hytte 7",
    description: "Hytten er bygget i 2009 og er hele 120 kvm. Fliselagt stue og gang med gulvvarme. 2 Bad og hele 5 soverom. Badstu og bod med fryseboks.",
    location: "Sjernarøy, Stavanger",
    beds: 5,
    bathrooms: 1,
    maxGuests: 10,
    pricePerNight: 0,
    images: [
      "https://usercontent.one/wp/furrehytter.no/wp-content/uploads/2025/05/7-front2.jpg",
      "https://usercontent.one/wp/furrehytter.no/wp-content/uploads/2025/05/7-stue.jpg",
      "https://usercontent.one/wp/furrehytter.no/wp-content/uploads/2025/05/7-kjokken.jpg",
      "https://usercontent.one/wp/furrehytter.no/wp-content/uploads/2025/05/Oversikt.jpeg",
    ],
    amenities: ["Sjøutsikt", "Badstu", "Gulvvarme", "Peis", "Kjøkken", "TV", "WiFi", "Sonos"],
    available: true,
    externalUrl: "https://furrehytter.no/hytter/h7",
  },
  {
    id: "furrehytter-h8",
    name: "Furrehytter Hytte 8",
    description: "Her er det plass til mange! Foruten alle tenkelige fasiliteter (tv med parabol og Chromecast, oppvaskmaskin, kaffetrakter, etc.) har denne en diger og delvis overbygget terrasse med nydelig utsikt.",
    location: "Sjernarøy, Stavanger",
    beds: 5,
    bathrooms: 2,
    maxGuests: 10,
    pricePerNight: 0,
    images: [
      "https://usercontent.one/wp/furrehytter.no/wp-content/uploads/2025/05/H8_Front.jpg",
      "https://usercontent.one/wp/furrehytter.no/wp-content/uploads/2025/11/H8_Livingroom-scaled.jpg",
      "https://usercontent.one/wp/furrehytter.no/wp-content/uploads/2025/11/H8_Kitchen-scaled.jpg",
      "https://usercontent.one/wp/furrehytter.no/wp-content/uploads/2025/11/H8_Bedroom1-scaled.jpg",
    ],
    amenities: ["Panoramautsikt", "Stor Terrasse", "Peis", "2 Bad", "Chromecast", "Kjøkken", "TV", "WiFi"],
    available: true,
    externalUrl: "https://furrehytter.no/hytter/h8",
  },
  {
    id: "furrehytter-h9",
    name: "Furrehytter Hytte 9",
    description: "Hytten er bygget i 2009 og er hele 120 kvm. Fliselagt stue og gang med gulvvarme. 2 Bad og hele 5 soverom. Bod med fryseboks.",
    location: "Sjernarøy, Stavanger",
    beds: 5,
    bathrooms: 2,
    maxGuests: 10,
    pricePerNight: 0,
    images: [
      "https://usercontent.one/wp/furrehytter.no/wp-content/uploads/2025/05/img_9704.jpg",
      "https://usercontent.one/wp/furrehytter.no/wp-content/uploads/2025/05/img_9716.jpg",
      "https://usercontent.one/wp/furrehytter.no/wp-content/uploads/2025/05/img_9705.jpg",
      "https://usercontent.one/wp/furrehytter.no/wp-content/uploads/2025/05/img_9712.jpg",
    ],
    amenities: ["Panoramautsikt", "Gulvvarme", "Peis", "2 Bad", "Kjøkken", "TV", "WiFi"],
    available: true,
    externalUrl: "https://furrehytter.no/hytter/h9",
  },
  {
    id: "furrehytter-h15",
    name: "Furrehytter Hytte 15 - Luksus",
    description: "Beliggende på bryggekanten. Luksushytte med 175 kvm. 5 soverom, 2 bad, peis og varmepumpe. Perfekt for store familier.",
    location: "Sjernarøy, Stavanger",
    beds: 5,
    bathrooms: 2,
    maxGuests: 9,
    pricePerNight: 0,
    images: [
      "https://usercontent.one/wp/furrehytter.no/wp-content/uploads/2025/05/hytte-nr15-stor.jpg",
      "https://usercontent.one/wp/furrehytter.no/wp-content/uploads/2025/10/H15_Stue-scaled.jpg",
      "https://usercontent.one/wp/furrehytter.no/wp-content/uploads/2025/10/H15_StueOppe-scaled.jpg",
      "https://usercontent.one/wp/furrehytter.no/wp-content/uploads/2025/05/boats_sunset_may22.jpeg",
    ],
    amenities: ["Bryggekant", "Luksus", "Peis", "Varmepumpe", "2 Bad", "Kjøkken", "TV", "WiFi", "Sonos"],
    available: true,
    externalUrl: "https://furrehytter.no/hytter/h15",
  },
  {
    id: "furrehytter-h16",
    name: "Furrehytter Hytte 16 - Luksus",
    description: "Beliggende på bryggekanten. Luksushytte med 175 kvm. 5 soverom, 2 bad, peis og varmepumpe. Helt lik H15, bare speilvendt.",
    location: "Sjernarøy, Stavanger",
    beds: 5,
    bathrooms: 2,
    maxGuests: 9,
    pricePerNight: 0,
    images: [
      "https://usercontent.one/wp/furrehytter.no/wp-content/uploads/2025/05/hytte-nr16-stor1.jpg",
      "https://usercontent.one/wp/furrehytter.no/wp-content/uploads/2025/10/H16_StueOppe-scaled.jpg",
      "https://usercontent.one/wp/furrehytter.no/wp-content/uploads/2025/10/H16_SovOppe_1-scaled.jpg",
      "https://usercontent.one/wp/furrehytter.no/wp-content/uploads/2025/05/boats_sunset_may22-1.jpeg",
    ],
    amenities: ["Bryggekant", "Luksus", "Peis", "Varmepumpe", "2 Bad", "Kjøkken", "TV", "WiFi", "Sonos"],
    available: true,
    externalUrl: "https://furrehytter.no/hytter/h16",
  },
  {
    id: "furrehytter-h19",
    name: "Furrehytter Hytte 19",
    description: "Beliggende på bryggekanten. Ferdigstilt 2018. 64 kvm med 2 soverom, 2 bad og gulvvarme. Perfekt for par eller liten familie.",
    location: "Sjernarøy, Stavanger",
    beds: 2,
    bathrooms: 2,
    maxGuests: 5,
    pricePerNight: 0,
    images: [
      "https://usercontent.one/wp/furrehytter.no/wp-content/uploads/2025/05/19-front.jpg",
      "https://usercontent.one/wp/furrehytter.no/wp-content/uploads/2025/05/MG_4731_edited.jpg",
      "https://usercontent.one/wp/furrehytter.no/wp-content/uploads/2025/05/MG_4747_edited.jpg",
      "https://usercontent.one/wp/furrehytter.no/wp-content/uploads/2025/05/MG_4743_edited.jpg",
    ],
    amenities: ["Bryggekant", "Gulvvarme", "2 Bad", "Moderne", "Kjøkken", "TV", "WiFi", "Sonos"],
    available: true,
    externalUrl: "https://furrehytter.no/hytter/h19",
  },
  {
    id: "furrehytter-h20",
    name: "Furrehytter Hytte 20",
    description: "Ferdigstilt i 2018, ligger vegg i vegg med H19. 92 kvm med 4 soverom, 2 bad og gulvvarme. Moderne og velutstyrt.",
    location: "Sjernarøy, Stavanger",
    beds: 4,
    bathrooms: 2,
    maxGuests: 8,
    pricePerNight: 0,
    images: [
      "https://usercontent.one/wp/furrehytter.no/wp-content/uploads/2025/05/20-front.jpg",
      "https://usercontent.one/wp/furrehytter.no/wp-content/uploads/2025/05/MG_4712_edited.jpg",
      "https://usercontent.one/wp/furrehytter.no/wp-content/uploads/2025/11/H20_Sov_1-scaled.jpg",
      "https://usercontent.one/wp/furrehytter.no/wp-content/uploads/2025/05/MG_4718_edited.jpg",
    ],
    amenities: ["Bryggekant", "Moderne", "Gulvvarme", "2 Bad", "Kjøkken", "TV", "WiFi"],
    available: true,
    externalUrl: "https://furrehytter.no/hytter/h20",
  },
  {
    id: "furrehytter-h21",
    name: "Furrehytter Hytte 21 - Premium",
    description: "Kan vi friste med den Mest Formidable Utsikten, stor terrasse, 2 bad med dusj og vegghengte toaletter – et med stort badekar, kjøkken, spisestue, stue og egen TV-stue, samt 6 soverom med totalt 12 sengeplasser?",
    location: "Sjernarøy, Stavanger",
    beds: 6,
    bathrooms: 2,
    maxGuests: 12,
    pricePerNight: 0,
    images: [
      "https://usercontent.one/wp/furrehytter.no/wp-content/uploads/2025/05/21_Front.jpg",
      "https://usercontent.one/wp/furrehytter.no/wp-content/uploads/2025/05/21_Terrasse.jpg",
      "https://usercontent.one/wp/furrehytter.no/wp-content/uploads/2025/05/21_Spisestue_Kjokken.jpg",
      "https://usercontent.one/wp/furrehytter.no/wp-content/uploads/2025/05/21_Badekar.jpg",
    ],
    amenities: ["Panoramautsikt", "Stor Terrasse", "Badekar", "2 Bad", "TV-stue", "Kjøkken", "WiFi", "Sonos", "Premium"],
    available: true,
    externalUrl: "https://furrehytter.no/hytter/h21",
  },
];

export class MemStorage implements IStorage {
  private users: Map<string, User>;
  private properties: Property[];
  private contactForms: ContactForm[];
  private bookingRequests: BookingRequest[];

  constructor() {
    this.users = new Map();
    this.properties = realProperties;
    this.contactForms = [];
    this.bookingRequests = [];
  }

  async getUser(id: string): Promise<User | undefined> {
    return this.users.get(id);
  }

  async getUserByUsername(username: string): Promise<User | undefined> {
    return Array.from(this.users.values()).find(
      (user) => user.username === username,
    );
  }

  async createUser(insertUser: InsertUser): Promise<User> {
    const id = randomUUID();
    const user: User = { ...insertUser, id };
    this.users.set(id, user);
    return user;
  }

  async getProperties(): Promise<Property[]> {
    return this.properties;
  }

  async getProperty(id: string): Promise<Property | undefined> {
    return this.properties.find((p) => p.id === id);
  }

  async setProperties(properties: Property[]): Promise<void> {
    this.properties = properties;
  }

  async saveContactForm(form: ContactForm): Promise<void> {
    this.contactForms.push(form);
  }

  async saveBookingRequest(booking: BookingRequest): Promise<void> {
    this.bookingRequests.push(booking);
  }
}

export const storage = new MemStorage();
